export default {
  lang: 0,
  langs: ["Hrvatski", "Engleski", "Njemački", "Talijanski"],
  langsEN: ["Croatian", "English", "German", "Italian"],
  langsIT: ["Croato", "Inglese", "Tedesco", "Italiano"],
  text: [
    //App
    "Početna",
    "O nama",
    "Limarija",
    "Strojna obrada",
    "Bravarija",
    "Galerija",
    "Kontakt",
    //HomeView
    "PROIZVODNJA ČELIČNIH KONSTRUKCIJA, PRERADA I OBRADA METALA, REZANJE LASEROM I SAVIJANJE METALA",
    "Vama na usluzi od 2001. godine!",
    "IZRADA METALNIH KONSTRUKCIJA, PRERADA I OBRADA METALA",
    "Pogon u Vodnjanu specijaliziran je za obradu metala, limariju i bravariju.",
    "u sklopu svog pogona može izrađivati metalne konstrukcije malih i velikih dimenzija do maksimum 20 tona. Zapošljavamo vrhunske bravare i zavarivače te u sklopu bravarije imamo sve potrebne strojeve (pile, CNC laser, CNC plazma, CNC savijačice s 4 osi).",
    "PROŠIRENJE RADNIH POGONA PREMA EUROPSKOM STANDARDU",
    "U skladu s vremenom pogon se stalno modernizira te je konkurentan na tržištu i prilagodljiv današnjim situacijama i različitim zahtjevima.",
    "Uz",
    "tehnološku modernizaciju",
    ", mnogo je učinjeno na proširenju radnih i poslovnih prostora kako bi odgovorali europskim standardima. Pogon zapošljava 15 djelatnika koji su stručni i osposobljeni za sve navedene poslove u preradi i obradi metala.Škamp d.o.o posluje sa hrvatskim, talijanskim i njemačkim tvrtkama. Naši proizvodi zadovoljavaju zahtjeve europskog tržišta.",
    "Škamp d.o.o posluje sa hrvatskim, talijanskim i njemačkim tvrtkama. Naši proizvodi zadovoljavaju zahtjeve europskog tržišta.",
    "VISOKA KVALITETA IZRADE METALNIH DIJELOVA PO ŽELJI KUPACA",
    "DJELATNOSTI",
    "Škamp d.o.o. se može pohvaliti da posjeduje vrhunski CNC laser AMADA7L 2kW fiber i dvije vrhunske savijačice",
    "Naša strojna obrada sastoji se od vrhunskih CNC glodalica i tokarilica",
    "Izrada metalnih konstrukcija, malih i velikih dimenzija do maksimum 20 tona",
    "GDJE SE NALAZIMO",
    "Sva prava pridržana",
    //O nama
    "O NAMA",
    "Škamp d.o.o. osnovan je 2001. godine. Naša tvrtka se u početku bavila samo ribarstvom te smo stoga odabrali naziv „Škamp“. Od 2012. širimo poslovanje i na djelatnost obrade metala te je otvoren izdvojeni pogon u Vodnjanu. Pogon u Vodnjanu specijaliziran je za obradu metala, limariju i bravariju. U skladu s vremenom pogon se stalno modernizira te je konkurentan na tržištu i prilagodljiv današnjim situacijama i različitim zahtjevima.",
    //Limarija
    "LIMARIJA",
    "Škamp d.o.o. se može pohvaliti da posjeduje vrhunski CNC laser AMADA7L 2kW fiber i dvije vrhunske savijačice.",
    "CNC SAVIJAČICE",
    "Naša tvrtka posjeduje dvije nove CNC savijačice s 4 osi. Dužina savijanja veće iznosi 4.1 m te snagu savijanja od 320 tona. Manja savijačica ima 3.1 m sa snagom od 135 tona.",
    "CNC LASER",
    "Škamp d.o.o posjeduje CNC laser vrhunske kvalitete 2 kw fiber. Stroj je noviji i predstavlja naš najjači atribut. Stroj može rezati obični čelik do 25 mm, inox i pocinčano do 10 mm. Stroj koristi novu",
    "fiber tehnologiju",
    "pomoću koje je brži i ljepše reže od običnog lasera.",
    //STROJNA OBRADA
    "STROJNA OBRADA",
    "Naša strojna obrada sastoji se od vrhunskih CNC glodalica i tokarilica.",
    "CNC TOKARILICA",
    "CNC tokarilica sa jednom glavom i šiljkom. Nosač alata može imati istovremeno 12 alata.",
    "CNC tokarilica namijenjena za manje komade. Ima 1 glavu i šiljaka. Nosač alata sadrži 12 alata.",
    "CNC tokarilica koja ima 2 glave. Stroj ima mogućnost i glodanja. Nosač alata može istovremeno imat 24 alata.",
    //Bravarija
    "BRAVARIJA",
    "Škamp d.o.o u sklopu svog pogona može izrađivati metalne konstrukcije, malih i velikih dimenzija do maximun 20 tona. Zapošljavamo vrhunske bravare i zavarivače te u sklopu bravarije imamo sve potrebne strojeve (pile, CNC laser, CNC plazma). Imamo dovoljno veliki prostor za izradu velikih konstrukcija i veliko iskustvo pri izradi istih.",
    "CNC PLAZMA",
    "Naša CNC plazma ima radni stol 2x6m. Ima mogućnost rezanja plazmom do 20mm i ima mogućnost rezanjem plinski do 200 mm debljine.",
    "Također posjedujemo pilu i vrhunsku CNC glodalicu koja ima 24 različita alata i površinu od 480x900mm.",
    "CNC plazma",
    "CNC glodalica",
    "Pila",
    //CONTACT
    "KONTAKTIRAJTE NAS",
    "IME",
    "PREZIME",
    "TVRTKA",
    "E-MAIL ADRESA",
    "UPIT",
    "Pošalji",
    "Molimo ispunite sva obavezna polja označena sa zvjezdicom.",
    "Hvala Vam na poslanom upitu.",
    "Kontaktirajte nas",
  ],
  textIT: [
    //App
    "Home page",
    "Chi siamo",
    "Lattoneria",
    "Lavorazione meccanica",
    "Carpenteria metallica",
    "Galleria",
    "Contatto",
    //HomeView
    "FABBRICAZIONE DI STRUTTURE IN ACCIAIO, LAVORAZIONE E TRATTAMENTO METALLI, TAGLIO LASER E PIEGATURA/CURVATURA METALLI",
    "Siamo a vostra disposizione sin dal 2001!",
    "REALIZZAZIONE DI STRUTTURE METALLICHE, LAVORAZIONE E TRATTAMENTO METALLI",
    "Il nostro stabilimento di Dignano è specializzato nella lavorazione metalli, lattoneria e carpenteria metallica.",
    "Nel suo stabilimento, l’impresa Škamp d.o.o. è in grado di realizzare strutture metalliche di piccole e grandi dimensioni fino ad un massimo di 20 tonnellate. Il nostro team è composto da fabbri e saldatori esperti e nell’ambito della carpenteria metallica disponiamo di tutti gli utensili e macchinari necessari (seghe, CNC taglio laser, CNC taglio plasma, CNC piegatrici 4 assi).",
    "AMPLIAMENTO DELLO STABILIMENTO PRODUTTIVO SECONDO GLI STANDARD EUROPEI",
    "Per stare al passo coi tempi, lo stabilimento viene costantemente modernizzato ed è competitivo sul mercato e facilmente adattabile alle situazioni ed esigenze specifiche dei tempi moderni.",
    "Oltre alla",
    "modernizzazione tecnologica",
    ", abbiamo investito molto anche nell’ampliamento dello stabilimento produttivo e degli uffici per renderli conformi agli standard europei. Lo stabilimento impiega 15 dipendenti esperti e abilitati a tutti i succitati lavori di lavorazione e trattamento metalli.",
    "Škamp d.o.o. collabora con imprese croate, italiane e tedesche. I nostri prodotti soddisfano i requisiti del mercato europeo.",
    "ALTA QUALITÀ DI PRODUZIONE DI COMPONENTI IN METALLO SU MISURA",
    "ATTIVITA'",
    "Škamp d.o.o. vanta la macchina laser CNC di ultima generazione AMADA 7L 2kW fiber e due piegatrici di massima qualità",
    "Il nostro reparto di lavorazione meccanica è dotato di fresatrici e torni CNC all’avanguardia",
    "Realizzazione di strutture metalliche di piccole e grandi dimensioni fino ad un massimo di 20 tonnellate",
    "DOVE CI TROVIAMO",
    "Tutti i diritti riservati",
    //O nama
    "CHI SIAMO",
    "La società a responsabilità limitata Škamp d.o.o. è stata fondata nel 2001. Dapprima la nostra impresa si occupava solo di pesca, infatti è per questa ragione che abbiamo scelto la denominazione „Škamp“ (scampo). Dal 2012 abbiamo ampliato le nostre attività anche alla lavorazione metalli e abbiamo costituito lo stabilimento distaccato di Dignano. Lo stabilimento di Dignano è specializzato nella lavorazione metalli, lattoneria e carpenteria metallica. Per stare al passo coi tempi, lo stabilimento viene costantemente modernizzato ed è competitivo sul mercato e facilmente adattabile alle situazioni ed esigenze specifiche dei tempi moderni.",
    //Limarija
    "LATTONERIA",
    "Škamp d.o.o. vanta la macchina laser CNC di ultima generazione AMADA 7L 2kW fiber e due piegatrici di massima qualità.",
    "CNC PIEGATRICI",
    "La nostra impresa dispone di due nove piegatrici CNC a 4 assi. La piegatrice più grande può raggiungere lunghezza di piegatura fino a 4.1 m e forza di piega fino a 320 ton. Quella più piccola raggiunge lunghezza di piegatura fino a 3.1 m e forza fino a 135 ton.",
    "CNC TAGLIO LASER ",
    "Škamp d.o.o. dispone di una macchina laser CNC di ultima generazione 2 kw fiber. Si tratta di un nuovo macchinario che è il nostro fiore all’occhiello. La macchina è in grado di tagliare l’acciaio normale fino a 25 mm, mentre quello inossidabile e zincato fino a 10 mm. La macchina vanta la nuova ",
    "tecnologia in fibra",
    "che le permette di tagliare meglio e più velocemente rispetto a un laser normale.",
    //STROJNA OBRADA
    "LAVORAZIONE MECCANICA",
    "Il nostro reparto di lavorazione meccanica è dotato di fresatrici e torni CNC all’avanguardia.",
    "TORNIO CNC",
    "Tornio CNC con un mandrino e punta. La torretta portautensili è in grado di ospitare 12 utensili contemporaneamente.",
    "Questo tornio CNC è ideale per pezzi più piccoli. È dotato di un mandrino e punta. La torretta portautensili ospita 12 utensili.",
    "Questo tornio CNC è dotato di 2 mandrini ed è capace di eseguire anche lavorazioni di fresatura. La torretta portautensili è in grado di ospitare 24 utensili contemporaneamente.",
    //Bravarija
    "CARPENTERIA METALLICA",
    "Nel suo stabilimento, Škamp d.o.o. è in grado di realizzare strutture metalliche di piccole e grandi dimensioni fino ad un massimo di 20 tonnellate. Il nostro team è composto da fabbri e saldatori esperti e nell’ambito della carpenteria metallica disponiamo di tutti gli utensili e macchinari necessari (seghe, CNC taglio laser, CNC taglio plasma). Disponiamo di uno spazio sufficientemente grande per realizzare grandi strutture e inoltre abbiamo una lunga esperienza nella loro costruzione.",
    "CNC PLAZMA",
    "Il nostro CNC taglio plasma ha una scrivania 2x6m. Ha la capacità di tagliare il plasma fino a 20 mm e ha la capacità di tagliare gas fino a 200 mm di spessore.",
    "Abbiamo anche una sega e una fresatrice CNC top che ha 24 utensili diversi e un'area di 480x900mm.",
    "CNC taglio plasma",
    "CNC fresatrice",
    "Sega",
    //CONTACT
    "CONTATTACI",
    "NOME",
    "COGNOME",
    "AZIENDA",
    "INDIRIZZO E-MAIL",
    "RICHIESTA",
    "INVIA",
    "Si prega di compilare tutti i campi obbligatori contrassegnati da un asterisco.",
    "Grazie per la vostra richiesta.",
    "Contattaci",
  ],
  textEN: [
    //App
    "Home",
    "About us",
    "Sheet metal",
    "Machining",
    "Metalwork",
    "Gallery",
    "Contact",
    //HomeView
    "MANUFACTURE OF STEEL STRUCTURES, METAL PROCESSING, LASER CUTTING AND METAL BENDING",
    "At your service since 2001!",
    "MANUFACTURE OF METAL STRUCTURES, PROCESSING AND METAL PROCESSING",
    "The plant in Vodnjan specializes in metal processing, sheet metal and locksmithing.",
    "as part of its plant can make metal constructions of small and large dimensions up to a maximum of 20 tons. We employ top locksmiths and welders and as part of the locksmith we have all necessary machines (saws, CNC laser, CNC plasma, CNC benders with 4 axis).",
    "EXTENSION OF WORK PLANTS ACCORDING TO THE EUROPEAN STANDARD",
    "In line with the times, the plant is constantly modernized and is competitive on the market and adaptable to today's situations and different requirements.",
    "Along with",
    "technological modernization ",
    ", much has been done to expand work and business premises to meet European standards. The plant employs 15 employees who are professional and qualified for all the above jobs in metal processing and processing. Škamp d.o.o does business with Croatian, Italian and German companies. Our products meet the requirements of the European market.",
    "Škamp d.o.o does business with Croatian, Italian and German companies. Our products meet the requirements of the European market.",
    "HIGH QUALITY OF MANUFACTURE OF METAL PARTS AT THE REQUEST OF CUSTOMERS",
    "ACTIVITIES",
    "Škamp d.o.o. can boast of owning a top notch CNC laser AMADA7L 2kW fiber and two great CNC benders",
    "Our machining consists of state-of-the-art CNC milling machines and lathes",
    "Production of metal structures, small and large dimensions up to a maximum of 20 tons",
    "WHERE WE'RE LOCATED",
    "All rights reserved",
    //O nama
    "ABOUT US",
    "Škamp d.o.o. was founded in 2001. At the beginning, our company was only engaged in fishing, so we chose the name „Shrimp“. Since 2012, we have been expanding our business to the metalworking business, and a separate plant has been opened in Vodnjan. The plant in Vodnjan specializes in metal processing, sheet metal and locksmithing. In accordance with the weather, the plant is constantly modernized and is competitive on the market and adaptable to today's situations and different requirements.",
    //Limarija
    "SHEET METAL",
    "Škamp d.o.o. can boast of owning a top notch CNC laser AMADA7L 2kW fiber and two great CNC benders",
    "CNC BENDERS",
    "Our company owns two new 4-axis CNC benders. The bending length is 4.1 m and the bending strength is 320 tons. The smaller bender has 3.1 m with a power of 135 tons.",
    "CNC LASER",
    "Škamp d.o.o has a CNC laser of top quality 2 kw fiber. The machine is newer and represents our strongest attribute. The machine can cut plain steel up to 25 mm, stainless steel and galvanized up to 10 mm. The machine uses new ",
    "fiber technology",
    "by which it cuts faster and more accurate than an ordinary laser.",
    //Strojna obrada
    "MACHINING",
    "Our machining consists of state-of-the-art CNC milling machines and lathes.",
    "CNC LATHE",
    "CNC lathe with one head and spike. The tool holder can have 12 tools at the same time.",
    "This CNC lathe is designed for smaller pieces. It has 1 head and spikes. The tool holder contains 12 tools.",
    "This CNC lathe has 2 heads. The machine also has the option of milling. The tool holder can have 24 tools at a time.",
    //Bravarija
    "METALWORK",
    "As part of its plant, Škamp d.o.o. can produce metal structures, small and large, up to a maximum of 20 tons. We employ top locksmiths and welders and within the locksmith we have all the necessary machines (saws, CNC laser, CNC plasma). We have enough space to make large structures and a lot of experience in making them.",
    "CNC PLASMA",
    "Our CNC plasma has a desk 2x6m. It has the ability to cut plasma up to 20mm and has the ability to cut gas up to 200mm thick.",
    "We also have a saw and a top CNC milling machine that has 24 different tools and an area of 480x900mm.",
    "CNC plasma",
    "CNC milling machine",
    "a saw",
    //CONTACT
    "CONTACT US",
    "NAME",
    "SURNAME",
    "COMPANY",
    "E-MAIL ADDRESS",
    "MESSAGE",
    "Submit",
    "Please fill in all required fields marked with an asterisk.",
    "Thank you for your inquiry.",
    "Contact us",
  ],
};
